# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05fae83819e432119e75316db943696a0a1809727165b1fc6509ec45032bca943d31ed423cdffe3ecb440518c6a5a3a66ca5c0f135319c59eed9bd2e2c2c13ae

test:
  secret_key_base: 3d56f2852ceb9e3046c1fccc839ada84526ae09d2e001db92a91b90d0afb31a170db04d7935ad9d20c2dbc243eadba59b86709a4007664285eeff9c3e054ef4b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
